// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXphiMZVfdKI65UoQOXfq9gGHvPFm9okY',
    appId: '1:42333396544:web:99031cc3b76534575509a5',
    messagingSenderId: '42333396544',
    projectId: 'registration-app-28291',
    authDomain: 'registration-app-28291.firebaseapp.com',
    storageBucket: 'registration-app-28291.appspot.com',
    measurementId: 'G-JSPF12FKM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4vDIxVqh4Z0n5x5hD-MUxlW0btTXRb8',
    appId: '1:42333396544:android:8b8580294d86421d5509a5',
    messagingSenderId: '42333396544',
    projectId: 'registration-app-28291',
    storageBucket: 'registration-app-28291.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNvCqzjtgMAXlIWOVD0BjCaW4modBeClE',
    appId: '1:42333396544:ios:a8f1456a4bcac1595509a5',
    messagingSenderId: '42333396544',
    projectId: 'registration-app-28291',
    storageBucket: 'registration-app-28291.appspot.com',
    iosClientId: '42333396544-84rbif55qrv4ki6tnl4rinskq6v4le2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.regestirationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNvCqzjtgMAXlIWOVD0BjCaW4modBeClE',
    appId: '1:42333396544:ios:46209c27b61f46905509a5',
    messagingSenderId: '42333396544',
    projectId: 'registration-app-28291',
    storageBucket: 'registration-app-28291.appspot.com',
    iosClientId: '42333396544-kps2fr6sgu46hh4cme75vu3vnl56s5dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.regestirationApp.RunnerTests',
  );
}
